name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          args: --output _dist
          install_dependencies: true
          publish_dir: _dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
